import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Suspense } from 'react';

import './globals.css';
import { Loading } from '@/components/shared';
import { DefaultProviders } from '@/components/providers';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Academic Management Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <Suspense fallback={<Loading />}>
          <DefaultProviders>{children}</DefaultProviders>
        </Suspense>
      </body>
    </html>
  );
}
